#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)
logo=$(lsb_release -i | cut -f 2-)



#Start of real code
#Help
if  [[ "$1"  ==  "help" ]]
then
echo 'Usage: bfetch [options]
options:
  beta: Show GPU
  short: Display only CPU, Memory and Disk
  update: Update bfetch'
exit 0
fi

#Logo :)
if [[ "$logo" == "Arch" ]]
then
cat /etc/bfetch/Logos/"$logo"
fi
if [[ "$logo" == "Debian" ]]
then
cat /etc/bfetch/Logos/"$logo"
fi

#Update
if [[ "$1" == "update" ]]
then
cd /tmp || exit
git clone https://github.com/Mati232411/bfetch.git
echo "Run the following command to update bfetch:"
echo "${bold}cd /tmp/bfetch && sudo make install${normal}"
exit 0
fi

#Real Code
echo
echo "${bold}OS -->${normal}"
lsb_release -i | cut -f 2-
echo
echo "${bold}Kernel -->${normal}"
uname -snrmv
echo
echo "${bold}CPU -->${normal}"
lscpu | grep "Model name:" | sed -r 's/Model name:\s{1,}//g'
echo

#GPU Beta
if [[ "$1" == "beta" ]]
then
echo GPU
lspci | grep "VGA compatible controller" | sed -r 's/Model name:\s1{1,}//g'
echo
fi

echo "${bold}Memory -->${normal}"
free -h | tr -s ' ' | sed '/^Mem/!d' | cut -d" " -f2
echo
echo "${bold}DISK -->${normal}"
df -h --exclude={devtmpfs,tmpfs}


